import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Nested Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <div>
    <div>333</div>
    {children}
  </div>
  )
}
