name: tests

on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd packages/common && npm install
      - run: cd auth && npm install && npm run test:ci
